# Generated by Django 2.2.6 on 2019-10-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='street_name',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
